name: "Automatic tests generation from commits messages for Python."
author: "Ivan Milev"
description: "AI powered action which will generate automatically functional and integration tests."
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'book'
  color: 'blue'