name: Auto-Test-Generator
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
jobs:
  generate:
    name: Changelog Generator
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: git diff-tree 342d87403b171dd19e5c74b2486a5b64a40e8584 e8f93fa4bbe7e14c51ee5d5498f443a3871c0927 -r --abbrev=40 --full-index -M -p --no-color
