name: Auto-Test-Generator
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  generate:
    name: Changelog Generator
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r pip_requirements.txt
      - run: python generate_tests_code.py
