name: Auto-Test-Generator
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
jobs:
  generate:
    name: Changelog Generator
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
#      - uses: actions/cache@v2
#        with:
#          path: ~/conda_pkgs_dir
#          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
#            hashFiles('environment.yml') }}
#      - uses: conda-incubator/setup-miniconda@v2
#        with:
#          activate-environment: diploma
#          environment-file: environment.yml
#          python-version: 3.9
#          auto-activate-base: false
#          use-only-tar-bz2: true
      - run: python generate_tests_code.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
