name: Auto-Test-Generator
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
jobs:
  generate:
    name: Changelog Generator
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
#      - uses: actions/cache@v2
#        with:
#          path: ~/conda_pkgs_dir
#          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml') }}
#      - uses: conda-incubator/setup-miniconda@v2
#        with:
#          activate-environment: diploma
#          environment-file: environment.yml
#          python-version: 3.9
#          auto-activate-base: false
#          use-only-tar-bz2: true
      - run: pip install PyDriller
      - run: git status
      - run: python generate_tests_code.py
      - run: git status
